INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Varesalg, m. moms','INDTAEGT','MOMS',0,0,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Varesalg, u. moms','INDTAEGT','EJMOMS',0,0,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Forsendelse m. moms','INDTAEGT','MOMS',0,0,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Forsendelse u. moms','INDTAEGT','EJMOMS',0,0,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Salg, tjenesteydelse m. moms','INDTAEGT','MOMS',0,0,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Salg, tjenesteydelse u. moms','INDTAEGT','EJMOMS',0,0,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Varekøb','UDGIFT','MOMS',100,100,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Varer, eget forbrug (INDTAEGTføres)','INDTAEGT','MOMS',0,0,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Køb af fremmed arbejde','UDGIFT','MOMS',100,100,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Køb af produktionsudstyr','UDGIFT','MOMS',100,100,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Leje af udstyr og maskiner','UDGIFT','MOMS',100,100,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Arbejdsbeklædning','UDGIFT','MOMS',100,100,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Markedsføring','UDGIFT','MOMS',100,100,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Websites','UDGIFT','MOMS',100,100,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Reklameartikler','UDGIFT','MOMS',100,100,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Kørsel i egen bil','UDGIFT','EJMOMS',100,0,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Erhvervstransport','UDGIFT','MOMS',100,100,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Porto og Fragt','UDGIFT','EJMOMS',100,0,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Rejseudgifter m. moms','UDGIFT','MOMS',100,100,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Rejseudgifter u. moms','UDGIFT','EJMOMS',100,0,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Taxi','UDGIFT','EJMOMS',100,0,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Hotel','UDGIFT','MOMS',100,75,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Restauration','UDGIFT','MOMS',100,25,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Repræsentation','UDGIFT','MOMS',25,25,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Bespisning i egne lokaler','UDGIFT','MOMS',100,100,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Leje af erhvervslokaler','UDGIFT','EJMOMS',100,0,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Rengøring','UDGIFT','MOMS',100,100,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Vedligehold af lokaler/ejendom','UDGIFT','MOMS',100,100,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Varme','UDGIFT','MOMS',100,100,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Olie, Gas, Kul til opvarming','UDGIFT','MOMS',100,100,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('El','UDGIFT','MOMS',100,100,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Vand','UDGIFT','MOMS',100,100,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Inventar','UDGIFT','MOMS',100,100,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('IT- og Teleudstyr','UDGIFT','MOMS',100,100,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Software','UDGIFT','MOMS',100,100,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Telefon, Internet og Mobil','UDGIFT','MOMS',100,100,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Fagblade','UDGIFT','MOMS',100,100,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Tidsskrifter','UDGIFT','EJMOMS',100,0,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Kontorartikler','UDGIFT','MOMS',100,100,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Advokat og Revisor','UDGIFT','MOMS',100,100,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Kursus','UDGIFT','MOMS',100,100,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Uddannelse','UDGIFT','EJMOMS',100,0,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Forsikringer','UDGIFT','EJMOMS',100,0,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Gebyrer o.lign.','UDGIFT','EJMOMS',100,0,'YDELSE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Andre indtægter u. moms','INDTAEGT','EJMOMS',0,0,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Andre indtægter m. moms','INDTAEGT','MOMS',0,0,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Andre udgifter u. moms','UDGIFT','EJMOMS',100,0,'VARE');
INSERT INTO KONTO (kontonavn, kontotype, momstype, indkomstfradrag, momsfradrag, varetype) VALUES ('Andre udgifter m. moms','UDGIFT','MOMS',100,100,'VARE');